name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Django Backend CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ./django
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: ./django/main_project
        run: |
          python manage.py test

  frontend:
    name: Next.js Frontend CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./web_app
        run: npm ci

      - name: Lint
        working-directory: ./web_app
        run: npm run lint

      - name: Build
        working-directory: ./web_app
        run: npm run build

      # - name: Test
      #   working-directory: ./web_app
      #   run: npm test -- --watchAll=false
