name: Deploy CDK Infrastructure

on:
  push:
    paths:
      - 'aws_cdk/**'
      - '.github/workflows/infra-deploy.yml'
    branches:
      - main

jobs:
  deploy:
    name: Bootstrap & Deploy CDK Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Configure AWS credentials
        # uses: aws-actions/configure-aws-credentials@v2
        # with:
        #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: ${{ env.AWS_REGION }}
        run: |
          echo "Configuring AWS credentials..."

      - name: Install CDK and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aws_cdk/requirements.txt
          npm install -g aws-cdk

      - name: CDK Bootstrap (safe to re-run)
        run: |
          echo "Bootstrapping CDK... (cdk bootstrap)"
        # run: cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }}
        # working-directory: aws_cdk

      - name: Deploy CDK Stack
        run: |
          echo "Deploying CDK stack... (cdk deploy --require-approval never)"
        # run: cdk deploy --require-approval never
        # working-directory: aws_cdk
